# Generated by Django 5.2.17 on 2026-08-30 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'capa_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签名')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'capa_tag',
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='工艺名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(verbose_name='工艺描述')),
                ('image', models.ImageField(blank=True, upload_to='capabilities/', verbose_name='展示图片')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capability.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='capability.tag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '工艺表',
                'verbose_name_plural': '工艺表',
                'db_table': 'capa_info',
                'ordering': ['order', 'title'],
            },
        ),
    ]
