# Generated by Django 5.2.17 on 2026-09-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='分类图片')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='首页显示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'capa_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='行业名')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
            ],
            options={
                'verbose_name': '行业表',
                'verbose_name_plural': '行业表',
                'db_table': 'capa_industry',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='材料名')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='材料图片')),
            ],
            options={
                'verbose_name': '材料表',
                'verbose_name_plural': '材料表',
                'db_table': 'capa_material',
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='工艺名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(verbose_name='工艺描述')),
                ('excerpt', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('image', models.ImageField(blank=True, upload_to='capabilities/', verbose_name='展示图片')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='首页显示')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('max_part_size', models.CharField(blank=True, max_length=100, verbose_name='最大加工尺寸')),
                ('tolerance', models.CharField(blank=True, max_length=100, verbose_name='公差精度')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capability.category', verbose_name='工艺分类')),
                ('industries', models.ManyToManyField(blank=True, to='capability.industry', verbose_name='服务行业')),
                ('materials', models.ManyToManyField(blank=True, to='capability.material', verbose_name='适用材料')),
            ],
            options={
                'verbose_name': '工艺表',
                'verbose_name_plural': '工艺表',
                'db_table': 'capa_info',
                'ordering': ['order', 'title'],
            },
        ),
    ]
