# Generated by Django 5.2.17 on 2026-08-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capability.category', verbose_name='工艺分类'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='tags',
            field=models.ManyToManyField(blank=True, to='capability.tag', verbose_name='行业标签'),
        ),
    ]
