# Generated by Django 5.2.17 on 2026-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0002_alter_capability_category_alter_capability_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=150, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.CharField(max_length=150, null=True, verbose_name='描述'),
        ),
    ]
