# Generated by Django 5.2.17 on 2026-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='项目名称')),
                ('value', models.CharField(max_length=200, verbose_name='规格数值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页事实表格',
                'verbose_name_plural': '首页事实表格',
                'db_table': 'home_fact_spec',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页FAQ',
                'verbose_name_plural': '首页FAQ',
                'db_table': 'home_faq',
                'ordering': ['order', 'id'],
            },
        ),
    ]
