# Generated by Django 5.2.17 on 2026-10-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='背景图')),
                ('primary_btn_text', models.CharField(blank=True, max_length=50, verbose_name='主按钮文字')),
                ('primary_btn_url', models.CharField(blank=True, max_length=200, verbose_name='主按钮链接')),
                ('secondary_btn_text', models.CharField(blank=True, max_length=50, verbose_name='次按钮文字')),
                ('secondary_btn_url', models.CharField(blank=True, max_length=200, verbose_name='次按钮链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'home_banner',
                'ordering': ['order', 'id'],
            },
        ),
    ]
