# Generated by Django 5.2.17 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='extra_html',
            field=models.TextField(blank=True, verbose_name='附加HTML（可选）'),
        ),
        migrations.AddField(
            model_name='banner',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=150, verbose_name='顶部小标签'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='主标题'),
        ),
    ]
