# Generated by Django 5.2.17 on 2026-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner_extra_html_banner_eyebrow_alter_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('value', models.CharField(max_length=50, verbose_name='数值')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='后缀')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页数据统计',
                'verbose_name_plural': '首页数据统计',
                'db_table': 'home_stat_item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
