# Generated by Django 5.2.17 on 2026-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_statitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='statitem',
            name='display_in',
            field=models.CharField(choices=[('partner', 'Trusted Partner CTA'), ('order', 'Ready to Order CTA'), ('both', 'Both CTAs')], default='both', max_length=20, verbose_name='显示位置'),
        ),
    ]
