# Generated by Django 5.2.17 on 2026-10-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_statitem_display_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='步骤标题')),
                ('description', models.TextField(verbose_name='步骤描述')),
                ('icon', models.CharField(blank=True, help_text="Bootstrap Icons 类名，如 'bi bi-file-earmark-arrow-up'", max_length=50, verbose_name='图标类名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页下单步骤',
                'verbose_name_plural': '首页下单步骤',
                'db_table': 'home_order_step',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='客户名称')),
                ('date_text', models.CharField(max_length=50, verbose_name='日期文本')),
                ('title', models.CharField(max_length=150, verbose_name='评价标题')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='评分（1-5）')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '客户评价',
                'verbose_name_plural': '客户评价',
                'db_table': 'home_testimonial',
                'ordering': ['order', 'id'],
            },
        ),
    ]
