"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s*1*s9pa+f46q82j*x%k!+yck4e4c%$^=e8k6rx^#tgcm$_lxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'user',
    'capability',
    'django_ckeditor_5',
    'home',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎，ORM的底层对接pymysql的核心引擎类
        'NAME': 'cncsite',  # 数据库名
        'USER': 'root',  # 数据库登录账号
        'PASSWORD': 'xiaopan123',  # 数据库密码（生产环境建议用环境变量保存，不硬编码）
        'HOST': 'localhost',  # 数据库IP地址
        'PORT': '3306',  # 数据库端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 静态文件 URL 前缀
STATIC_URL = '/static/'

# 开发阶段静态文件来源目录，添加项目根目录的 static 文件夹作为额外的静态文件源
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),   # 指向根目录的 static 文件夹
]

# 生产环境静态文件收集目录（开发阶段不生效，部署前运行 collectstatic）
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')  # 收集时用，开发阶段可暂时不管


AUTH_USER_MODEL = 'user.Reguser'  # 格式为 应用名.模型名（user.Reguser），必须放在第一次迁移之前

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # MEDIA_ROOT：文件在服务器磁盘上的实际存储路径

MEDIA_URL = '/media/'  # MEDIA_URL：浏览器访问这些文件的URL前缀，比如 /media/avatar.jpg

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""CKEditor5 配置项"""
# 控制上传权限: "staff", "authenticated", "any"
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff" 
# 允许上传所有文件类型 (默认为 False, 仅允许图片)
CKEDITOR_5_ALLOW_ALL_FILE_TYPES = False 
# 限制上传文件大小 (单位: MB)
CKEDITOR_5_MAX_FILE_SIZE = 5 
# 限制上传文件的扩展名
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpg', 'jpeg', 'png', 'gif', 'webp'] 
# CKEditor5 工具栏定制
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'bulletedList', 'numberedList', 'blockQuote', '|',
            'imageUpload', 'insertTable', '|',
            'undo', 'redo', '|',
            'sourceEditing',   # ← 新增：源码编辑按钮
        ],
        'height': 300,
        'language': 'zh-cn',
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3', '|',
            'bulletedList', 'numberedList', '|',
            'imageUpload', 'insertTable', 'mediaEmbed',
        ],
        'toolbar': [
            'heading', '|',
            'outdent', 'indent', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'code', 'subscript', 'superscript', 'highlight', '|',
            'link', 'bulletedList', 'numberedList', 'todoList', '|',
            'blockQuote', 'insertImage', 'insertTable', 'mediaEmbed', 'codeBlock', '|',
            'undo', 'redo', '|',
            'sourceEditing',   # ← 新增：源码编辑按钮
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
            ],
            'styles': ['full', 'alignLeft', 'alignCenter', 'alignRight'],
        },
        'language': 'zh-cn',
    },
}