# Generated by Django 5.2.17 on 2026-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reguser',
            options={'verbose_name': 'User_info', 'verbose_name_plural': 'User_info'},
        ),
        migrations.AlterField(
            model_name='reguser',
            name='head_img',
            field=models.ImageField(blank=True, upload_to='head_image/', verbose_name='head_img'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='nickname',
            field=models.CharField(default='', max_length=32, verbose_name='nickname'),
        ),
    ]
