# Generated by Django 5.2.17 on 2026-08-24 04:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_reguser_options_alter_reguser_head_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country/region'),
        ),
    ]
