# Generated by Django 5.2.17 on 2026-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reguser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='head_img',
        ),
        migrations.RemoveField(
            model_name='reguser',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='reguser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='mobile'),
        ),
    ]
