# Generated by Django 5.2.17 on 2026-08-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_reguser_head_img_remove_reguser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reguser',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
