# Generated by Django 5.2.17 on 2026-08-25 14:54

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_reguser_options_alter_reguser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reguser',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='reguser',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2, verbose_name='国家地区'),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='电话号码'),
        ),
    ]
