# Generated by Django 5.2.17 on 2026-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reguser_options_alter_reguser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址'),
        ),
    ]
